wandb_version: 1

model:
  desc: null
  value: TrajectoryWindowCount
env:
  desc: null
  value: MiniGrid-KeyCorridorS3R3-v0
seed:
  desc: null
  value: 1
intr_coeff:
  desc: null
  value: 0.005
window_size:
  desc: null
  value: 3
no_skills:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694369402.419956
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.6
      5: 0.15.5
      8:
      - 4
      - 5
