wandb_version: 1

model:
  desc: null
  value: ''
performance metric:
  desc: null
  value: extrinsic reward
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690385736.349594
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.6
      5: 0.15.5
      8:
      - 4
      - 5
